[project]
name = "vitrine-2025"
version = "0.1.0"
description = "Web server to control a KUKA robot"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.122.0",
    "pyads>=3.5.0",
]
